'''

yW2OO.py

Postprocessor for yWriter5 HTML export to make it suitable for Open/LibreOffice Writer

* This script removes several useless tags generated by yWriter5, such as table and font specification.
* This script sets Chapter headings to "Heading 2" and modifies the String "Chapter" if you wish.
* This script sets Scene headings to "Heading 4".
* It is assumed that in Writer, default paragraphs will be set to "First-line indent" manually or by macro.  
* This script sets the first paragraph of each chapter and scene to "Heading 6"
* It is assumed that in Writer, "Heading 6" paragraphs will be set to "Text body" manually or by macro.
* This script converts "italic" and "bold" into "emphasized" and "strong" according to Writer's character styles.
* This script converts US dashes into european dashes if spaced.
* This script converts spaces before dashes and ellipses into non-breaking space characters.
* This script removes empty paragraphs within scenes.

Created on 2018-10-02

@author: Peter Triesberger
@version: 1.2.0

'''

HTMLfileName = "Exported Project.html" # yWriter5 default
stringBeforeChapterNumber = "Chapter " # US: Chapter; Germany: Kapitel;  could also be a dash
stringAfterChapterNumber = "" # could be a dash
#dash = "&ndash;" # &mdash; (---) or &ndash; (--)


replaceList =[
    "<p align='justify'><i>&nbsp;</i></p>\n<p class='Para'>|<H6>|",
    "<br /><br /><br /><center>* * *</center><br /><br />\n\n<p class='Para'>|<H4>* * *</H4>\n<H6>|",
    "<table align=center border=0 width=790>||",
    "<tr><td>||",
    #"&mdash;|"+dash+"|",
    " &mdash;|&nbsp;&ndash;|",
    "&mdash; |&ndash; |",
    "<font name='arial' size=+1>||",
    "</font>||",
    "</td></tr></table>||",
    "<p align='justify'><i>&nbsp;</i></p>||",
    "<p class='Para'></p>||",
    "</b></center>|"+stringAfterChapterNumber+"</H2>|",
    "<center><b>|<H2>|",
    "Chapter |"+stringBeforeChapterNumber+"|",
    "<b>|<STRONG>|",
    "</b>|</STRONG>|",
    "<i>|<EM>|",
    "</i>|</EM>|",
    #" "+dash+"|&nbsp;"+dash+"|",
    " &hellip;|&nbsp;&hellip;|",
    ]

def searchAndReplace(processData, replaceList):   
    for line in replaceList:
        replaceItem = line.split("|") 
        processData = processData.replace(replaceItem[0],replaceItem[1])
    return(processData)


if __name__ == '__main__':
    try:     
        HTMLfile = open(HTMLfileName,'r')
        HTMLdata = HTMLfile.read()
        HTMLfile.close()
        HTMLdata = searchAndReplace(HTMLdata, replaceList)
        HTMLfile = open(HTMLfileName,'w')
        HTMLfile.write(HTMLdata)
        HTMLfile.close()
        message = '"'+HTMLfileName+'" successfully converted.'
        print(message)
    except:
        message = 'ERROR: Cannot access "'+HTMLfileName+'"!'
        print(message)
    
    